//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumaneSociety.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-NHO0NO3H\\SQLEXPRESS;Initial Catalog=HumaneSociety2;Integrated " +
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GARRETSLAPTOP\\SQLEXPRESS02;Initial Catalog=HumaneSociety2;Integrated " +
>>>>>>> 6d7c8fef15bab68fd1b284db3c372e129ee73f09
            "Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string HumaneSociety2ConnectionString {
            get {
                return ((string)(this["HumaneSociety2ConnectionString"]));
            }
        }
    }
}
